### ISSUE TITLE
Conflicting dependencies between grpcio-status and google-cloud logging

### ISSUE THREAD

**Issue by duybtr** [duybtr/tbi#111]
@Sendaria  @yinlertc 
Quick fix: https://stackoverflow.com/questions/78807804/issue-installing-google-cloud-logging-with-pipenv
Update the pipfile when Google resolves the issue: https://github.com/googleapis/python-logging/issues/899

**Comment by duybtr** [comment]
Fixed for now. Downgraded grpcio-status to 1.62.0

**Comment by Sendaria** [comment]
Ok thanks
